const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_NO_CONTENT_204_STATUS = 204;
const HTTP_NOT_FOUND_400_STATUS = 400;
const HTTP_NOT_FOUND_401_STATUS = 401;
const HTTP_NOT_FOUND_404_STATUS = 404;
const PORT = process.env.PORT || '3001';

module.exports = {
    HTTP_OK_STATUS,
    HTTP_CREATED_STATUS,
    HTTP_NO_CONTENT_204_STATUS,
    HTTP_NOT_FOUND_404_STATUS,
    HTTP_NOT_FOUND_400_STATUS,
    HTTP_NOT_FOUND_401_STATUS,
    PORT,
};